### ISSUE TITLE
TrendingVideosResponse

### ISSUE THREAD

**Issue by 666bsw** [b5i/YouTubeKit#27]
TrendingVideosResponse always empty

let responce: TrendingVideosResponse = TrendingVideosResponse()
let result = try? await responce.getCategoryContentThrowing(forIdentifier: "", youtubeModel: ytm, useCookies: true)
what am i doing wrong?

**Comment by b5i** [comment]
> TrendingVideosResponse always empty
> 
> 
> 
> let responce: TrendingVideosResponse = TrendingVideosResponse()
> 
> let result = try? await responce.getCategoryContentThrowing(forIdentifier: "", youtubeModel: ytm, useCookies: true)
> 
> what am i doing wrong?

Hello! You should never instantiate a response (except for storage reasons) and get them from their static method `sendThrowingRequest` or the non-throwing one.

The reason you get nothing is because the `getCategoryContentThrowing` method looks at the `requestParams` property of your response and, as it's empty because of the manual initialization, it won't find any parameter and so will return nothing.

You can take a look at the [documentation](https://github.com/b5i/YouTubeKit/blob/d2a2220596141f61f7200578d19eb8e4ea74855e/Sources/YouTubeKit/YouTubeResponseTypes/Trending/TrendingVideosResponse.swift#L16) of the `getCategoryContent` method for more information about the usage of it.

**Comment by 666bsw** [comment]
The library organization is not very clear from the documentation). Can you provide a more specific example that will work? ))

/// Dictionnary associating a category identifier (usually like "Music" or "Film" contained in the ``TrendingVideosResponse/requestParams`` as the dictionnary keys) with an array of videos (representing the trendig videos of the tab identifier). It can be seen as some cache for every type of category.

Supposing myInstance.requestParams["MyIdentifier"] != nil (but can be an empty string)


var myInstance: TrendingVideosResponse = TrendingVideosResponse()
myInstance.getCategoryContent(forIdentifier: "", youtubeModel: ytm) { result in
            switch result {
            case .success(let newInstance):
                print("\(newInstance)")
                myInstance.mergeTrendingResponse(newInstance)
            case .failure(let error):
                print("err \(error)")
            }
}

"err Something between returnType or params haven't been added where it should, returnType in TrendingVideosResponse.requestTypes and params in TrendingVideosResponse.requestParams"

additionally for: myInstance.mergeTrendingResponse(newInstance)
"Mutation of captured var 'myInstance' in concurrently-executing code; this is an error in the Swift 6 language mode"

**Comment by b5i** [comment]
> Hello! The organization of the library is not yet very clear from the documentation). That's why I'm asking for help. Can you provide a more specific example that will work? ))

No problem, I'm working on improving it!

> Supposing myInstance.requestParams["MyIdentifier"] != nil (but can be an empty string)

"(but can be an empty string)" means `myInstance.requestParams["MyIdentifier"] == ""` is not a problem.

This code should be like `var myInstance = try await TrendingVideosResponse.sendThrowingRequest(youtubeModel: ytm, data: [:])` or 
```swift
TrendingVideosResponse.sendNonThrowingRequest(youtubeModel: ytm, data: [:]) { result in
       switch result {
             case .success(let newInstance):
                 print("\(newInstance)")
                 myInstance.mergeTrendingResponse(newInstance)
             case .failure(let error):
                 print("err \(error)")
      }
 }
```

> "err Something between returnType or params haven't been added where it should, returnType in TrendingVideosResponse.requestTypes and params in TrendingVideosResponse.requestParams"

This error is caused by the fact that, as you instantiate your response manually, requestParams is empty and won't find the `""` (empty string) key in it. Therefore, `myInstance.requestParams[""] == nil` and the above condition isn't met.

> additionally for: myInstance.mergeTrendingResponse(newInstance) "Mutation of captured var 'myInstance' in concurrently-executing code; this is an error in the Swift 6 language mode"

I can't reproduce the issue, I know some Xcode versions have issues with Swift 6's new concurrency features. Could you check that and give me the complete code that caused this issue to raise?
 
> what should it contain requestParams? : [.videos, .playlists.....] ?

It's a dictionary of strings where the values are the parameters YouTubeKit gives to YouTube to obtain certain categories of content.
<img width="472" alt="Screenshot 2024-09-19 at 7 00 49 PM" src="https://github.com/user-attachments/assets/16c0ac74-f436-4311-846a-131865c7e193">

**Comment by 666bsw** [comment]
Thank you very much!
something started to work out, I got the answer on the key
myInstance.requestParams = ["Music" : "Music"]

and why in the example the key "Music" contains the value "4gINGgt5...."? what is this?

Swift 6's new concurrency - the full example is above - you can't just mutate something from the closure.

Thank you)

**Comment by b5i** [comment]
> Thank you very much! something started to work out, I got the answer on the key myInstance.requestParams = ["Music" : "Music"]

It should be more like `myInstance.requestParams = ["Music" : "4gINGgt5...."]`. Otherwise YouTube won't give you the right tab back (see my explanation below).

> and why in the example the key "Music" contains the value "4gINGgt5...."? what is this?

You can see the dictionary like this: [Display name : special YouTube param]. YouTube needs that weird token to understand that you want to get the category represented by the "Display name".

> Swift 6's new concurrency - the full example is above - you can't just mutate something from the closure.

Oh ok, I was using async/await that's the reason, you're right!

> Thank you)

My pleasure!

**Comment by 666bsw** [comment]
Thank you again, you were very helpful and explained everything very quickly and clearly.
